import os

def get_relative_md_files(base_dir, scan_dir):
    """
    掃描 scan_dir 下所有的 *.md 檔案，排除 .git，並取得相對於 base_dir 的 forward-slash 路徑
    """
    if not os.path.exists(scan_dir):
        return []
    
    paths = []
    # 遞迴遍歷
    for root, dirs, files in os.walk(scan_dir):
        # 排除 .git
        if ".git" in root or "/.git/" in root or "\\.git\\" in root:
            continue
        for file in files:
            if file.endswith(".md"):
                full_path = os.path.join(root, file)
                # 取得相對於 base_dir 的相對路徑
                rel = os.path.relpath(full_path, base_dir).replace('\\', '/')
                paths.append(rel)
                
    # 進行 Ordinal 排序
    return sorted(paths)

def generate_manifest(manifest_name, display_name, prefix, base_dir, scan_dir, out_file):
    # 掃描相對路徑
    entries = get_relative_md_files(base_dir, scan_dir)
    
    # 建立內容
    lines = []
    lines.append(f"# {manifest_name}")
    # 移除時間戳記，改為 UCL_DocsModuleManifestGenerator.cs 格式
    lines.append(f"# Auto-generated by UCL_DocsModuleManifestGenerator.cs")
    lines.append('# DO NOT EDIT BY HAND - re-run "Tools/UCL/Generate All Localized Docs Manifests" instead.')
    lines.append(f"# Module: {display_name} (prefix={prefix})")
    
    # C# 端 Path.Combine 生成的 Source 路徑包含 Windows 的反斜線，故我們用本地 path separator 且帶上磁碟機英文字母大寫
    abs_scan_dir = os.path.abspath(scan_dir)
    # 確保磁碟機字母大寫 (e.g. d:\ -> D:\)
    if len(abs_scan_dir) > 1 and abs_scan_dir[1] == ':':
        abs_scan_dir = abs_scan_dir[0].upper() + abs_scan_dir[1:]
    
    lines.append(f"# Source: {abs_scan_dir}")
    lines.append(f"# Entries: {len(entries)}")
    for rel in entries:
        lines.append(rel)
        
    content = "\n".join(lines) + "\n" # 確保結尾有換行且使用 \n 換行符
    
    # 確保資料夾存在
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    
    # 寫入 (UTF-8, LF)
    with open(out_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
        
    print(f"Generated {manifest_name} -> {out_file} with {len(entries)} entries.")

def main():
    root = r"d:\Unity\emblem-of-valor"
    
    # 1. RCG Localized Docs Manifest
    generate_manifest(
        manifest_name="RCG_LocalizedDocsManifest",
        display_name="EmblemOfValorDocuments",
        prefix="eov_docs",
        base_dir=os.path.join(root, "EmblemOfValorDocuments"),
        scan_dir=os.path.join(root, "EmblemOfValorDocuments"),
        out_file=os.path.join(root, "CardGame", "Assets", "Resources", "RCG_LocalizedDocsManifest.txt")
    )
    
    # 2. UCL Localized Docs Manifest
    generate_manifest(
        manifest_name="UCL_LocalizedDocsManifest",
        display_name="UCL_Core",
        prefix="ucl_core",
        base_dir=os.path.join(root, "CardGame", "Assets", "UCL", "UCL_Core"),
        scan_dir=os.path.join(root, "CardGame", "Assets", "UCL", "UCL_Core", "Docs~"),
        out_file=os.path.join(root, "CardGame", "Assets", "UCL", "UCL_Core", "Resources", "UCL_LocalizedDocsManifest.txt")
    )
    
    # 3. UCL Steam Localized Docs Manifest
    generate_manifest(
        manifest_name="UCL_Steam_LocalizedDocsManifest",
        display_name="UCL_Steam",
        prefix="ucl_steam",
        base_dir=os.path.join(root, "CardGame", "Assets", "UCL", "UCL_Modules", "UCL_Steam"),
        scan_dir=os.path.join(root, "CardGame", "Assets", "UCL", "UCL_Modules", "UCL_Steam", "Docs~"),
        out_file=os.path.join(root, "CardGame", "Assets", "UCL", "UCL_Modules", "UCL_Steam", "Resources", "UCL_Steam_LocalizedDocsManifest.txt")
    )

if __name__ == "__main__":
    main()
