"""T81 BattleSet scanner — 掃 RCG_BattleSet/ 過濾命名規則 + 排序 + 產 checkable test order.

職責：對 .BuiltinModules 下 RCG_BattleSet/*.json 套命名 regex
       (Map_Type_LvN_Enemy or Type_LvN_Enemy 變體) → parsed entry
       → 按 Lv 升冪 + 名稱排序 → 寫 qa_test_order.md (checkable markdown)

命名規則接受（per Tim 11:30 task brief 範例 Boss_Cave_Lv1_Echidna）:
  <Type>_<Map>_Lv<N>_<Enemy...>     — Boss_Cave_Lv1_Echidna
  <Map>_<Type>_Lv<N>_<Enemy...>     — Cave_Boss_Lv2_Satyr
  <Type>_Lv<N>_<Enemy...>           — Boss_Lv1_Beleth (no map)
  <Map>_<Type>_Lv<N>_<Enemy...>_N   — Cave_Elite_Lv2_Empusa_SnowWoman_2

不符規則 (Tim 說 skip)：
  All3DEnemies / Bandit / 沒 _LvN_ 段的舊命名
"""
from __future__ import annotations
import json
import os
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple


_HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))
# T-PATH-02: .BuiltinModules 走 layout-agnostic resolver, 不再寫死 CardGame/Assets/.BuiltinModules
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
from AgentCommands._lib import tavern_paths as _tp  # noqa: E402
DEFAULT_BATTLESET_DIR = os.path.join(
    str(_tp.BUILTIN_MODULES_DIR), "ModulesRoot",
    "Modules", "Core", "UCL_Assets", "RCG_BattleSet"
)
DEFAULT_OUTPUT = os.path.join(
    PROJECT_ROOT, "AgentCommands", "QA_Battle_Logs", "qa_test_order.md"
)


# 區塊職責：核心命名 regex
# 物理意義：抓 Lv<N> 段為錨點，前後拆解 type/map + enemy
# 數值影響：不命中 → entry 標 skip 不入 checklist
# 已知 type 詞彙
TYPE_TOKENS = {"Boss", "Elite", "Normal"}
# 已知 map 詞彙（按目前 dir 內出現）
MAP_TOKENS = {"Cave", "Forest", "Default", "DefaultScene"}


def parse_battleset_name(stem: str) -> Optional[Dict[str, Any]]:
    """把 file stem 拆成 {type, map, lv, enemy}.

    Returns None 表不符規則 → skip
    """
    m = re.search(r"_Lv(\d+)_", stem)
    if not m:
        return None
    lv = int(m.group(1))
    before = stem[: m.start()]   # e.g. "Cave_Boss" or "Boss_Cave" or "Boss" or "Normal"
    after = stem[m.end():]        # enemy 部分 e.g. "Echidna" or "Empusa_SnowWoman_2"

    # 拆 before — 找 type / map
    before_tokens = before.split("_") if before else []
    type_tok = None
    map_tok = None
    for t in before_tokens:
        if t in TYPE_TOKENS and type_tok is None:
            type_tok = t
        elif t in MAP_TOKENS and map_tok is None:
            map_tok = t
    # 沒 type 但只有 type-like 的（如 'Normal_Lv1_BattleMaid'）也接受
    if type_tok is None and len(before_tokens) == 1 and before_tokens[0] in TYPE_TOKENS:
        type_tok = before_tokens[0]

    if type_tok is None:
        # 還是抓不到 type token → skip
        return None

    return {
        "stem": stem,
        "type": type_tok,
        "map": map_tok or "(unspec)",
        "lv": lv,
        "enemy": after or "(unknown)",
    }


def scan_dir(battleset_dir: str) -> Tuple[List[Dict[str, Any]], List[str]]:
    """掃 dir，回 (matched, skipped)."""
    matched, skipped = [], []
    if not os.path.isdir(battleset_dir):
        return matched, skipped
    for fn in sorted(os.listdir(battleset_dir)):
        if not fn.endswith(".json"):
            continue
        stem = fn[:-5]
        if stem.startswith("_") or stem.startswith("."):
            continue
        parsed = parse_battleset_name(stem)
        if parsed is None:
            skipped.append(stem)
        else:
            matched.append(parsed)
    return matched, skipped


def render_checklist(matched: List[Dict[str, Any]], skipped: List[str]) -> str:
    """渲染 markdown checkable test order。"""
    matched.sort(key=lambda e: (e["lv"], e["type"] != "Normal", e["type"] != "Elite", e["map"], e["enemy"]))
    by_lv = defaultdict(list)
    for e in matched:
        by_lv[e["lv"]].append(e)

    out = []
    out.append("# 🎯 QA Battle Test Order")
    out.append("")
    out.append(f"> Auto-generated by `scan_battle_sets.py` at {datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00','Z')}")
    out.append(f"> 規則: `<Map>_<Type>_Lv<N>_<Enemy>` 命名命中才入清單；舊格式 skip。")
    out.append("")
    out.append("## 進度")
    out.append("")
    out.append(f"- Total matched: **{len(matched)}** entries")
    out.append(f"- Skipped (not conforming): {len(skipped)}")
    out.append(f"- Lv 分布:")
    for lv in sorted(by_lv.keys()):
        out.append(f"  - Lv{lv}: {len(by_lv[lv])} entries")
    out.append("")
    out.append("---")
    out.append("")
    out.append("## 規則說明")
    out.append("")
    out.append("- **每組合 5 plays** (per Tim 拍板) → 平均分數")
    out.append("- 每完成 5 plays 後填 `分數=N.N` + 勾 ✅")
    out.append("- 評分尺度 1-5（純量化 + agent subjective hybrid，per claude 自由意志）")
    out.append("- 由易至難 (Lv 升冪 → Type Normal/Elite/Boss → Map → Enemy)")
    out.append("- 跑單筆建議：先 PlayMode enter → BattleSetup 換 enemy_comp → 5 plays → RecordBattleResult → mark check")
    out.append("")
    out.append("---")
    out.append("")

    for lv in sorted(by_lv.keys()):
        out.append(f"## Lv {lv} ({len(by_lv[lv])} entries)")
        out.append("")
        out.append("| ✓ | Type | Map | Enemy | BattleSet ID | 分數 | Notes |")
        out.append("|---|---|---|---|---|---|---|")
        for e in by_lv[lv]:
            type_emoji = {"Normal": "⚔️", "Elite": "💎", "Boss": "👹"}.get(e["type"], "❓")
            out.append(
                f"| [ ] | {type_emoji} {e['type']} | {e['map']} | `{e['enemy']}` | `{e['stem']}` | _ /5 | _ |"
            )
        out.append("")

    if skipped:
        out.append("---")
        out.append("")
        out.append(f"## ⚠ Skipped ({len(skipped)} non-conforming names)")
        out.append("")
        out.append("以下未命中 `<Map>_<Type>_LvN_<Enemy>` 規則。跳過（per Tim 拍板）。")
        out.append("")
        out.append("<details><summary>展開列表</summary>")
        out.append("")
        for s in skipped[:200]:
            out.append(f"- `{s}`")
        if len(skipped) > 200:
            out.append(f"- ...({len(skipped) - 200} more)")
        out.append("")
        out.append("</details>")
        out.append("")

    return "\n".join(out)


def main(argv: Optional[List[str]] = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass

    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=DEFAULT_BATTLESET_DIR)
    ap.add_argument("--out", default=DEFAULT_OUTPUT)
    ap.add_argument("--print", action="store_true", help="also print to stdout")
    args = ap.parse_args(argv)

    matched, skipped = scan_dir(args.dir)
    md = render_checklist(matched, skipped)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"✅ Scanned {len(matched)+len(skipped)} files")
    print(f"   matched: {len(matched)} / skipped: {len(skipped)}")
    by_lv = defaultdict(int)
    for e in matched:
        by_lv[e["lv"]] += 1
    for lv in sorted(by_lv.keys()):
        print(f"   Lv{lv}: {by_lv[lv]}")
    print(f"💾 Wrote: {args.out}")

    if args.print:
        print()
        print(md[:2000])
        if len(md) > 2000:
            print(f"...({len(md)-2000} more chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
